name: Hello World

on: workflow_dispatch

jobs:
  Hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greeting
        run: echo"Hello Github Actions"

      - name: Print Multiple Lines
        run: |
          echo "This step runs several shell commands."
          echo "Today's runner is: $RUNNER_OS"
          echo "The repository is: $GITHUB_REPOSITORY" 
